"""empty message

Revision ID: 5d0b0496cdbc
Revises: 6418f5264dfd
Create Date: 2017-10-01 22:56:57.416619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0b0496cdbc'
down_revision = '6418f5264dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('bucketlists', sa.Column('belongs_to', sa.Integer(), nullable=True))
    op.alter_column('bucketlists', 'bucket_name',
               existing_type=sa.VARCHAR(length=240),
               nullable=False)
    op.create_unique_constraint(None, 'bucketlists', ['bucket_name'])
    op.create_foreign_key(None, 'bucketlists', 'users', ['belongs_to'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucketlists', type_='foreignkey')
    op.drop_constraint(None, 'bucketlists', type_='unique')
    op.alter_column('bucketlists', 'bucket_name',
               existing_type=sa.VARCHAR(length=240),
               nullable=True)
    op.drop_column('bucketlists', 'belongs_to')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
